sudo: required
services:
  - docker

before_install:
  - docker build -t saud/docker-react -f Dockerfile.dev .

script:
  - docker run saud/docker-react npm run test -- --coverage
  
 deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env1"
  bucker_name: "elasticbeanstalk-us-east-2-057457200263"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key:
      secure: $AWS_SECRET_KEY
